### PR TITLE
Add iso-surface analysis and visualization codes for Gray-Scott simulation

### PR DESCRIPTION
**Pull request by keichi**
- isosurface: Reads variable U and and extracts the iso-surface using VTK
- render_isosurface: Reads and renders iso-surface mesh data
- find_blobs: Reads iso-surface mesh data and detects connected components
- compute_curvature: Compute curvature of iso-surface mesh

### CODE REVIEW

**Comment by pnorbert** [comment]
What version of VTK is required?

**Comment by pnorbert** [comment]
How should VTK be built? I am trying with VTK 8.1.0 that VisIt built for itself and that build is missing vtkRenderView.h

**Comment by keichi** [comment]
I've tested it with VTK 8.1.2 installed using Homebrew.

**Comment by keichi** [comment]
Can you try enabling the following components when building VTK?

- vtkFiltersGeometry
- vtkIOImage
- vtkIOXML
- vtkRenderingOpenGL2
- vtkViewsInfovis

**Comment by keichi** [comment]
I just built VTK 8.2.0 on a fresh Ubuntu 16.04 VM without enabling or disabling any component, and all the components I'm using were installed by default (including vtkRenderView.h).

**Comment by pnorbert** [comment]
It works for me now. It will be merged after we are done with the European tutorials. Thanks a lot.

**Comment by pnorbert** [comment]
I will take care of the conflict on README.md as well.

**Comment by keichi** [comment]
Great, thanks.

**Comment by keichi** [comment]
@pnorbert I've rebased on current master and resolved the conflicts. Please consider merging.

**Pull request merged**
